[project]
name = "do_function_addons"
version = "0.1.0"
description = "DigitalOcean functions addons. Typed Event and Context class."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
